### ISSUE TITLE
Can not specify which port / address needs to be used when redirecting http -> https

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/configurable-http-proxy#120] opened 2017-08-17 01:00 UTC
Related to https://github.com/jupyterhub/jupyterhub/issues/1289.

Use case:

CHP is listening on port 8000 (since it's running as user Nobody) but kubernetes maps that to port 80 on an external IP. We want to do HTTP -> HTTPS redirects here, but CHP assumes that bind IP == connect IP, and hence redirects users to its local IP address, which can not be resolved from the external internet.

**Comment by minrk** [comment] 2017-08-17 09:24
I don't think this is related to #1289 because unlike the Hub, CHP never specifies from internal configuration what ip anyone should connect to.

CHP doesn't use the bind address (which is ~always 0.0.0.0) for this, it uses the Host header so that it should be the same as the connect ip for a properly assembled request. My guess is the upstream proxy is not passing through the Host header. We could try to figure out what the proxied Host was (e.g. `X-Forwarded-Host`), or we could require that the upstream proxy [preserve host headers](https://docs.oracle.com/cd/E40518_01/studio.310/studio_install/src/cidi_studio_reverse_proxy_preserve_host_headers.html) for this feature.

Can you inspect the headers to see what kubernetes is passing?

If there is an additional upstream proxy, it probably makes more sense for *it* to do the HTTP->HTTPS redirect, anyway.

**Comment by clancychilds** [comment] 2018-11-20 14:35
I think, IIUC, the problem is less about the host, and more about the port?
Inside the k8s cluster, the HTTPS service is listening on 8443 and the HTTP service on 8000. These are portforwarded on the loadbalancer from 443 and 80 respectively.
When `--port 8443` and `--redirect-port 8000` are set, then a user trying to connect to <external>:80 is portforwarded to <internal>:8000 which is 301'd to <external>:8443, which doesn't work.
It may need an option like `--redirect-to 443` which would be used on https://github.com/jupyterhub/configurable-http-proxy/blob/master/bin/configurable-http-proxy#L349 to that port (rather than the listen.port)

**Comment by minrk** [comment] 2019-01-08 10:59
closed by #187

**Closed by minrk** 2019-01-08 10:59 UTC
Labels: needs: more user information
